### ISSUE TITLE
Could not run `python3 -m vecino --help`

### ISSUE THREAD

**Issue by bzz** [src-d/vecino#2]
Sorry if I have missed something, but after working around #1 on running `python3 -m vecino --help` (by analogy with https://github.com/src-d/ast2vec/) I got

```
python3 -m vecino --help
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/alex/src-d/vecino/vecino/__init__.py", line 1, in <module>
    from vecino.similar_repositories import SimilarRepositories
  File "/Users/alex/src-d/vecino/vecino/similar_repositories.py", line 7, in <module>
    from vecino.environment import initialize
  File "/Users/alex/src-d/vecino/vecino/environment.py", line 3, in <module>
    from ast2vec import setup_logging, ensure_bblfsh_is_running_noexc, install_enry
ImportError: cannot import name 'setup_logging'
```

Allthough README does not mention it, from [vecino/__main__.py#L10](https://github.com/src-d/vecino/blob/develop/vecino/__main__.py#L10) It looks like CLI is an intended usage of Vecino.

**Comment by vmarkovtsev** [comment]
Works.
