### ISSUE TITLE
Bblfsh instructions are not documented in the README

### ISSUE THREAD

**Issue by eiso** [src-d/vecino#3]
After `pip3 install vecino`.

And following the README, I get the following errors:

```
WARNING:bblfsh:Failed to connect to the Docker daemon and ensure that the Babelfish server is running. Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

The above one makes sense that bblfsh needs to be running but this should be documented in the README since people won't know this.

The following error I believe is related to bblfsh not running but still putting it here:

```
INFO:similar_repos:Loaded nBOW model: ast2vec.bow.NBOW().load(source=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/vecino/similar_repositories.py", line 50, in __init__
    self._id2vec, self._df, log_level=verbosity, **(repo2nbow_kwargs or {}))
  File "/usr/lib/python3.6/site-packages/ast2vec/repo2/nbow.py", line 21, in __init__
    self._uasts2bow = Uasts2BOW(id2vec, docfreq, lambda x: x.response.uast)
  File "/usr/lib/python3.6/site-packages/ast2vec/model2/source2bow.py", line 21, in __init__
    self._reverse_vocabulary = [None] * len(vocabulary)
  File "/usr/lib/python3.6/site-packages/ast2vec/id2vec.py", line 61, in __len__
    return len(self._tokens)
AttributeError: 'Id2Vec' object has no attribute '_tokens'
```

**Comment by vmarkovtsev** [comment]
I fixed this error - it happened because of the unsynced vecino <-> astvec.
