### ISSUE TITLE
The bblfsh/server:v0.7.0 used in README doesn't exist anymore

### ISSUE THREAD

**Issue by billmetangmo** [src-d/vecino#7]
###  As you can see here: https://hub.docker.com/u/bblfsh/ 

I tried to install bblfsh server using bblfsh/bblfshd:v2.0.0 , the lowest available but it failed with error:

`INFO:id2vec:Reading /root/.source{d}/id2vec/default.asdf...
Traceback (most recent call last):
  File "/usr/local/bin/vecino", line 11, in <module>
    load_entry_point('vecino==0.1.6a0', 'console_scripts', 'vecino')()
  File "/usr/local/lib/python3.5/dist-packages/vecino/__main__.py", line 72, in main
    "vocabulary_max": args.vocabulary_max}
  File "/usr/local/lib/python3.5/dist-packages/vecino/similar_repositories.py", line 27, in __init__
    self._id2vec = Id2Vec(log_level=verbosity).load(backend=backend)
  File "/usr/local/lib/python3.5/dist-packages/modelforge/model.py", line 121, in load
    self._load_tree(tree)
  File "/usr/local/lib/python3.5/dist-packages/ast2vec/id2vec.py", line 27, in _load_tree
    self.construct(embeddings=tree["embeddings"].copy(),
MemoryError
`

  Any advice ?

**Comment by vmarkovtsev** [comment]
Thanks for noticing, updated the readme.

```
docker run -d --privileged -p 9432:9432 --name bblfshd bblfsh/bblfshd                 
docker exec -it bblfshd bblfshctl driver install --all
```

Regarding the MemoryError, it loads 1 gig of vectors into the RAM on this line. Not enough free memory is available :(

**Comment by billmetangmo** [comment]
Thanks. It works fine with the updated README & more memory :) .
